name: 'Get IP address'
description: 'Get IP address'

runs:
  using: "composite"
  steps:
    - name: Check IP
      id: ip
      shell: bash
      run: echo "::set-output name=ip-address::$(curl -s https://api.ipify.org)"

    - name: Set additional env variables
      shell: bash
      run: |
        echo "IP_ADDRESS=${{ steps.ip.outputs.ip-address }}" >> $GITHUB_ENV